ci: add job to test on qemu in github workflow
Signed-off-by: Huaqi Fang <578567190@qq.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -63,6 +63,12 @@ jobs:
             libgmp-dev libmpfr-dev libmpc-dev gawk libz-dev libssl-dev device-tree-compiler libncursesw5-dev libncursesw5 \
             python3 python3-pip mtools
           sudo pip3 install git-archive-all
+          mkdir -p buildroot/dl
+          if [ ! -f buildroot/dl/nuclei-qemu-2022.04-linux-x64.tar.gz ] ; then
+            wget -P buildroot/dl https://nucleisys.com/upload/files/toochain/qemu/nuclei-qemu-2022.04-linux-x64.tar.gz
+          fi
+          mkdir -p prebuilt_tools
+          tar -xzf buildroot/dl/nuclei-qemu-2022.04-linux-x64.tar.gz -C prebuilt_tools
 
       # Build Freeloader
       - name: Build freeloader for ${{ matrix.core }} - ${{ matrix.boot_mode }}
@@ -77,10 +83,27 @@ jobs:
           echo "Generate QEMU Disk"
           echo ">>> Apply workaround: change TIMERCLK_FREQ from 32768 to 1000000"
           sed -i "s/32768/1000000/" conf/demosoc/*.dts
+          make CORE=${{ matrix.core }} BOOT_MODE=${{ matrix.boot_mode }} freeloader
+          cp work/demosoc/freeloader/freeloader.elf work/demosoc/freeloader_qemu.elf
           make CORE=${{ matrix.core }} BOOT_MODE=${{ matrix.boot_mode }} DISK_SIZE=128 gendisk
           RUNQEMUSH=work/demosoc/run_qemu.sh
-          echo "qemu-system-riscv64 -M nuclei_u,download=flashxip -smp 8 -m 256M -bios freeloader/freeloader.elf -nographic -drive file=disk.img,if=sd,format=raw" > $RUNQEMUSH
+          echo "qemu-system-riscv64 -M nuclei_u,download=flashxip -smp 8 -m 256M -bios freeloader_qemu.elf -nographic -drive file=disk.img,if=sd,format=raw" > $RUNQEMUSH
           chmod +x $RUNQEMUSH
+          echo ">>> Reset workaround and source code, and rebuilt freeloader"
+          git reset --hard
+          make freeloader
+
+      # Run on qemu
+      - name: Run and test on qemu for ${{ matrix.core }} - ${{ matrix.boot_mode }}
+        run: |
+          cd work/demosoc
+          # $(cat run_qemu.sh) is workaround for directly run bash run_qemu.sh
+          # If do kill it will just kill bash process, the qemu process is not killed
+          # SIGTERM is better for kill qemu
+          timeout --foreground -s SIGTERM 8m $(cat run_qemu.sh) > >(tee run_qemu.log) || {
+              if cat run_qemu.log | grep "Run /init" ; then echo "Kernel boot successfully" ; else echo "Kernel boot failed" && exit 1; fi;
+              if cat run_qemu.log | grep "Welcome to" ; then echo "Pass simulation" && exit 0; else echo "Failed init process" && exit 1; fi;
+          }
       
       - name: Upload bootimages for ${{ matrix.core }} - ${{ matrix.boot_mode }}
         uses: actions/upload-artifact@v2.2.0
@@ -97,6 +120,7 @@ jobs:
           path: |
             work/demosoc/boot.zip
             work/demosoc/freeloader/freeloader.elf
+            work/demosoc/freeloader_qemu.elf
             work/demosoc/disk.img
             work/demosoc/run_qemu.sh
 
