ci: comment run qemu step because p0 sdk cannot run on qemu.
Signed-off-by: guibing <guibing@nucleisys.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -108,21 +108,21 @@ jobs:
           make genboot
 
       # Run on qemu
-      - name: Run and test on qemu for ${{ matrix.soc }} - ${{ matrix.core }} - ${{ matrix.boot_mode }}
-        run: |
-          QEMU_PATH=$(pwd)/prebuilt_tools/linux_qemu/bin:$(pwd)/prebuilt_tools/qemu/bin
-          export PATH=${QEMU_PATH}:$PATH
-          export SOC=${{ matrix.soc }} CORE=${{ matrix.core }} BOOT_MODE=${{ matrix.boot_mode }}
-          cd work/$SOC
-          # show qemu version
-          bash show_qemu.sh
-          # $(cat run_qemu.sh) is workaround for directly run bash run_qemu.sh
-          # If do kill it will just kill bash process, the qemu process is not killed
-          # SIGTERM is better for kill qemu
-          timeout --foreground -s SIGTERM 5m $(cat run_qemu.sh) > >(tee run_qemu.log) || {
-              if cat run_qemu.log | grep "Run /init" ; then echo "Kernel boot successfully" ; else echo "Kernel boot failed" && exit 1; fi;
-              if cat run_qemu.log | grep "Welcome to" ; then echo "Pass simulation" && exit 0; else echo "Failed init process" && exit 1; fi;
-          }
+     # - name: Run and test on qemu for ${{ matrix.soc }} - ${{ matrix.core }} - ${{ matrix.boot_mode }}
+     #   run: |
+     #     QEMU_PATH=$(pwd)/prebuilt_tools/linux_qemu/bin:$(pwd)/prebuilt_tools/qemu/bin
+     #     export PATH=${QEMU_PATH}:$PATH
+     #     export SOC=${{ matrix.soc }} CORE=${{ matrix.core }} BOOT_MODE=${{ matrix.boot_mode }}
+     #     cd work/$SOC
+     #     # show qemu version
+     #     bash show_qemu.sh
+     #     # $(cat run_qemu.sh) is workaround for directly run bash run_qemu.sh
+     #     # If do kill it will just kill bash process, the qemu process is not killed
+     #     # SIGTERM is better for kill qemu
+     #     timeout --foreground -s SIGTERM 5m $(cat run_qemu.sh) > >(tee run_qemu.log) || {
+     #         if cat run_qemu.log | grep "Run /init" ; then echo "Kernel boot successfully" ; else echo "Kernel boot failed" && exit 1; fi;
+     #         if cat run_qemu.log | grep "Welcome to" ; then echo "Pass simulation" && exit 0; else echo "Failed init process" && exit 1; fi;
+     #     }
 
       - name: Upload bootimages for ${{ matrix.soc }} - ${{ matrix.core }} - ${{ matrix.boot_mode }}
         uses: actions/upload-artifact@v4
